#@TYPE: Machine
#@NAME: Albertow QEMU x86-64 machine
#@DESCRIPTION: QEMU x86-64 machine for Albertow read-only rootfs

require conf/machine/qemux86-64.conf

MACHINEOVERRIDES =. "qemux86-64:"
SERIAL_CONSOLES = "115200;ttyS0"
IMAGE_FSTYPES = "squashfs"
