#@TYPE: Machine
#@NAME: Albertow QEMU ARMv8 machine
#@DESCRIPTION: QEMU ARMv8 machine for Albertow read-only rootfs

require conf/machine/qemuarm64.conf

MACHINEOVERRIDES =. "qemuarm64:"
SERIAL_CONSOLES = "115200;ttyAMA0"
IMAGE_FSTYPES = "squashfs"
