#@TYPE: Machine
#@NAME: QEMU ARMv8 machine
#@DESCRIPTION: QEMU ARMv8 machine for read-only rootfs

require ${COREBASE}/meta/conf/machine/qemuarm64.conf

SERIAL_CONSOLES = "115200;ttyAMA0"
IMAGE_FSTYPES = "squashfs"
