#@TYPE: Machine
#@NAME: QEMU x86-64 machine
#@DESCRIPTION: QEMU x86-64 machine for read-only rootfs

require ${COREBASE}/meta/conf/machine/qemux86-64.conf

SERIAL_CONSOLES = "115200;ttyS0"
IMAGE_FSTYPES = "squashfs"
